#!/bin/bash
if [ -d ~/.sbm ]
then sudo rm -rf /root/.sbm ~/.sbm/listaiso ~/.sbm/listaiso_grub ~/.sbm/lol ~/.sbm/os ~/.sbm/os_grub ~/.sbm/risoluzioni ~/.sbm/risoluzioni1 ~/.sbm/iso ~/.sbm/tipoiso
else
mkdir ~/.sbm
fi 
cd /usr/share/sbm/
sudo rm -rf 1* 2* 3* 4* 5* 6* 7* 8* 9* 0*
exit 0