#!/bin/bash

#menuentry to remove
#mtr=$(sed -e '/./{H;$!d;}' -e 'x;/$isotoremove/!d;' /etc/grub.d/50_ubuntu_iso)

#id menuentry
rtot=$(wc -l  ~/.sbm/listaiso | awk '{print $1}')
toremove=$(cat ~/.sbm/isotoremove) 
idm=$(grep -n -i -x "$toremove" ~/.sbm/listaiso| awk '{print $1}'| tr -cd [:digit:])
GD=$(($rtot-$idm+1))
#cancella paragrafo $GD
sudo awk 'BEGIN{RS=""; ORS="\n\n"}; NR!='$GD'' /etc/grub.d/50_iso > ~/.sbm/50_iso
sudo rm -rf /etc/grub.d/50_iso && sudo mv ~/.sbm/50_iso /etc/grub.d/
sudo chmod a+x /etc/grub.d/50_iso
sudo update-grub
buc /usr/share/sbm/success.mc
exit 0