#!/bin/bash
# os=$(grep -i -e menuentry /boot/burg/burg.cfg | awk -F[\'\"] '{print $2}'| sed '/./!d'|wc -l)
# linenum=$os
# while (( linenum >="0" )) ;
# do
# input[$linenum]=$(grep -i -e menuentry /boot/burg/burg.cfg | awk -F[\'\"] '{print $2}'| sed '/./!d'| head -$linenum | /usr/bin/tail -1)
# echo ${input[$linenum]} >> ~/.sbm/tempos 
# i=$(($linenum-1))
# linenum=$i
# done
# df=$(awk -F "GRUB_DEFAULT=" '{print $2}' /etc/default/burg)
# dfrm=$(($df+1))
# # echo "df=" $df
# # echo "dfrm=" $dfrm
# sed -i '/'${input[$dfrm]}'/d' ~/.sbm/tempos 
# echo ${input[$dfrm]} >> ~/.sbm/os 
# cat ~/.sbm/tempos >> ~/.sbm/os
# cat ~/.sbm/os

os=$(grep -i -e menuentry /boot/burg/burg.cfg | awk -F[\'\"] '{print $2}'| sed '/./!d'|wc -l)
linenum=$os
while (( linenum >="0" )) ;
do
input[$linenum]=$(grep -i -e menuentry /boot/burg/burg.cfg | awk -F[\'\"] '{print $2}'| sed '/./!d'| head -$linenum | /usr/bin/tail -1)
echo ${input[$linenum]}
i=$(($linenum-1))
linenum=$i
done
exit 0