#!/bin/bash
cd ~/.sbm
wget http://dl.dropbox.com/u/877248/version
now=$(cat ~/.sbm/version|tr -d ".")
rm -rf ~/.sbm/version
installed=$(cat /usr/share/sbm/version|tr -d ".")
#installed=$(cat /usr/share/sbm/version)
if [ "$now" -gt "$installed" ] ; 
then
buc /usr/share/sbm/updateavaible.mc
fi
exit 0