#!/bin/bash
rtot=$(wc -l  ~/.sbm/os | awk '{print $1}')
osd=$(cat ~/.sbm/defaultos)  
OSYS=$(grep -n -i -x "$osd" ~/.sbm/os| awk '{print $1}'| tr -cd [:digit:])
GD=$(($rtot-$OSYS))
sudo sed -i 's/GRUB_DEFAULT=[0-9]*/GRUB_DEFAULT='$GD'/g' /etc/default/burg
# for (( I=0 ; I<${#input[*]} ; I++ ))
# do
# if [ "${input[$I]}" = "$operativesystem" ]; then
# GD=$(($I-1))
# xterm -e "sudo sed -i 's/GRUB_DEFAULT=[0-9]*/GRUB_DEFAULT=$GD/g' /etc/default/burg"
# fi    
# done 
